### ISSUE TITLE
Avoid false binary input

### ISSUE THREAD

**Issue by ChildishGiant** [gura-conf/gura#8]
If I were to have a value such as 0b0011 (a valid hex colour) what stops it being read as binary and just parsed as 3?

**Comment by Genarito** [comment]
Hi! 
The prefix `0b` denotes that what follows should be interpreted as an integer with base 2 (i.e. interpreting an integer from a binary number). If what you need is to use the value as required by HTML, CSS, or any other tool that requires a color in its hexadecimal representation, you can simply use [strings](https://gura.netlify.app/docs/spec/#string). In case you need to interpret the decimal number from the hexadecimal value you can use the `0x` prefix. E.g.:

```
hex_value: "0b0011"
hex_value_int: 0x0b0011
```

You could use the [Jware Config Lang Translator](https://config-translator.netlify.app/) as a playground :D

**Comment by ChildishGiant** [comment]
Thank you for answering my question! ☺️
